'''
Generates the type stubs for Client and AsyncClient.

The API methods are defined once, in BaseClient, and return whatever the
subclass's request methods return: a response in Client, and an awaitable of a
response in AsyncClient. Inline annotations can't express that, so this script
writes stubs in which Client's API methods return ``httpx.Response`` and
AsyncClient's are coroutines returning ``httpx.Response``.

API methods are the public methods of BaseClient annotated ``-> Any``. Public
methods defined directly on Client or AsyncClient are copied into the stubs
with their own annotations.

Run from the repository root after changing any client method signature:

    python tools/generate_client_stubs.py

tests/client_stubs_test.py fails if the checked-in stubs are out of date.
'''

import ast
import copy
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLIENT_DIR = os.path.join(ROOT, 'schwab', 'client')

HEADER = '''\
# Generated by tools/generate_client_stubs.py from schwab/client/base.py and
# schwab/client/{module}.py. Do not edit by hand.

import datetime
from collections.abc import Callable, Iterable
from typing import Any

import httpx

from ..orders.generic import OrderBuilder
from .base import BaseClient

'''


def _parse_class(module, class_name):
    with open(os.path.join(CLIENT_DIR, module + '.py')) as f:
        tree = ast.parse(f.read())
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == class_name:
            return node
    raise ValueError('class {} not found in {}'.format(class_name, module))


def _public_methods(class_node):
    for node in class_node.body:
        if (isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
                and not node.name.startswith('_')):
            yield node


def _is_api_method(node):
    return (isinstance(node.returns, ast.Name) and node.returns.id == 'Any')


def _stub_args(args):
    '''Returns the argument list with defaults replaced by ``...``.'''
    args = copy.deepcopy(args)
    args.defaults = [ast.Constant(Ellipsis) for _ in args.defaults]
    args.kw_defaults = [
        None if d is None else ast.Constant(Ellipsis)
        for d in args.kw_defaults]
    return ast.unparse(args)


def _stub(node, *, is_async, returns=None):
    prefix = 'async def' if is_async else 'def'
    if returns is None:
        returns = ast.unparse(node.returns) if node.returns else 'Any'
    return '    {} {}({}) -> {}: ...\n'.format(
            prefix, node.name, _stub_args(node.args), returns)


def generate(module, class_name, is_async):
    base = _parse_class('base', 'BaseClient')
    own = _parse_class(module, class_name)

    lines = [HEADER.format(module=module)]
    lines.append('class {}(BaseClient):\n'.format(class_name))

    for node in _public_methods(own):
        lines.append(_stub(
                node, is_async=isinstance(node, ast.AsyncFunctionDef)))

    own_names = {node.name for node in _public_methods(own)}
    for node in _public_methods(base):
        if _is_api_method(node) and node.name not in own_names:
            lines.append(_stub(
                    node, is_async=is_async, returns='httpx.Response'))

    return ''.join(lines)


STUBS = (
    ('synchronous', 'Client', False),
    ('asynchronous', 'AsyncClient', True),
)


def stub_path(module):
    return os.path.join(CLIENT_DIR, module + '.pyi')


def main():
    for module, class_name, is_async in STUBS:
        with open(stub_path(module), 'w') as f:
            f.write(generate(module, class_name, is_async))
        print('Wrote', os.path.relpath(stub_path(module), ROOT))


if __name__ == '__main__':
    sys.exit(main())
